server:
  port: 8082

spring:
  application:
    name: disaster-emergency-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/resq_emergency_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: SuperSecretKeyForResQConnectDevDeployment2026
